### ISSUE TITLE
No .npy file found 

### ISSUE THREAD

**Issue by Jaiming724** [Kyubyong/dc_tts#48]
I have installed all the libraries but it keeps giving me this:

Traceback (most recent call last):
  File "train.py", line 160, in <module>
    if gs > hp.num_iterations: break
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 1014, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1279, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.IOError: [Errno 2] No such file or directory: 'mels/LJ024-0008.npy'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)
  File "/home/alansmithans/dc_tts/data_load.py", line 113, in _load_spectrograms
    return fname, np.load(mel), np.load(mag)
  File "/home/alansmithans/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: 'mels/LJ024-0008.npy'

**Comment by Jaiming724** [comment]
Sorry I misread the prepo. I thought running train.py would first run prepo automatically.
