### ISSUE TITLE
Error occur when runnning "python train.py 2"

### ISSUE THREAD

**Issue by tkgmomosheep** [Kyubyong/dc_tts#55]
I have ran "train.py 1 " to >400k.

When I run "train.py 2", I ran in to OOM.
Below is the log from the command.
https://pastebin.com/3hgn7rnd

I am using a 2080 ti and have 64gb ram.
I am using python3.7, cuda 10.0 and tensorflow 1.14.0

**Comment by ssnake** [comment]
try python2

**Comment by tkgmomosheep** [comment]
Thanks for the reply, I'll try later on.

Btw I looked at the loss in teosorboard and it's not what a expected. Any idea what might be wrong?

![2019-10-14 01_42_02-TensorBoard](https://user-images.githubusercontent.com/8298025/66719551-fc8ee500-ee23-11e9-8642-b186908fe80b.jpg)

**Comment by ssnake** [comment]
My variant. The model has been taught on russian dataset (common voice)
![image](https://user-images.githubusercontent.com/193212/66982392-a4bfda80-f0be-11e9-81e2-807ef14278ef.png)

**Comment by ssnake** [comment]
@tkgmomosheep have you overcome your issue? I run into it too, but It happened after I replaced huge dataset with particular dataset with 180 files in it

**Comment by tkgmomosheep** [comment]
> @tkgmomosheep have you overcome your issue? I run into it too, but It happened after I replaced huge dataset with particular dataset with 180 files in it

My dataset only have 13x files in it. I have to lower thr batch size from 32 to 16 to get it to work. I don't know if there is any workaround except from lowering batch size.

**Comment by ssnake** [comment]
yes, it helped. Reduced  batch size from 32 to 16 and it started to work

**Comment by Traincraft101** [comment]
How do you lower the batch size?

**Comment by ssnake** [comment]
look at `hyperparams.py` at the end of it just set new value  `B = 16`

**Comment by Traincraft101** [comment]
I can't get my dataset to work. I keep getting 

(python36) C:\Anaconda3\envs\Python36\dc_tts-master>python prepo.py
2019-12-16 17:19:37.471344: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "prepo.py", line 17, in <module>
    fpaths, _, _ = load_data() # list
  File "C:\Anaconda3\envs\Python36\dc_tts-master\data_load.py", line 48, in load_data
    fname, _, text = line.strip().split("|")
ValueError: not enough values to unpack (expected 3, got 1)

But for some reason it works fine with the LJ speech dataset!

**Comment by Pritzier** [comment]
Yeah, lowering the batch size worked for me too.
