### ISSUE TITLE
[SOLVED] ValueError: not enough values to unpack (expected 5, got 3)

### ISSUE THREAD

**Issue by Traincraft101** [Kyubyong/dc_tts#56]
This error occurs whenever I run train.py 1 or prepo.py
2019-11-02 16:08:41.766338: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    g = Graph(num=num); print("Training Graph loaded")
  File "train.py", line 40, in __init__
    self.L, self.mels, self.mags, self.fnames, self.num_batch = get_batch()
  File "C:\Python36\dc_tts-master\data_load.py", line 92, in get_batch
    fpaths, text_lengths, texts = load_data() # list
  File "C:\Python36\dc_tts-master\data_load.py", line 65, in load_data
    fname, _, text, is_inside_quotes, duration = line.strip().split("|")
ValueError: not enough values to unpack (expected 5, got 3)

**Comment by Traincraft101** [comment]
I tried using "VS" instead of "LJ" for the transcript and wave files.
