### ISSUE TITLE
AttributeError when running train.py 1

### ISSUE THREAD

**Issue by Traincraft101** [Kyubyong/dc_tts#57]
I keep getting this error:
C:\Python36\dc_tts-master>python train.py 1
2019-11-03 15:55:08.766811: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    g = Graph(num=num); print("Training Graph loaded")
  File "train.py", line 40, in __init__
    self.L, self.mels, self.mags, self.fnames, self.num_batch = get_batch()
  File "C:\Python36\dc_tts-master\data_load.py", line 99, in get_batch
    fpath, text_length, text = tf.train.slice_input_producer([fpaths, text_lengths, texts], shuffle=True)
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'slice_input_producer'

**Comment by Traincraft101** [comment]
solved

**Comment by saifkazi** [comment]
how did you solved it ?

**Comment by Traincraft101** [comment]
> 
> 
> how did you solved it ?

I wish I knew but I completely forget, it's been so long

**Comment by ghost** [comment]
Maybe this can helps https://stackoverflow.com/questions/57858219/loss-passed-to-optimizer-compute-gradients-should-be-a-function-when-eager-exe/58952358#58952358
