### ISSUE TITLE
Synthesize error   --- ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by fathimad11** [Kyubyong/dc_tts#73]
Traceback (most recent call last):
  File "synthesize.py", line 67, in <module>
    synthesize()
  File "synthesize.py", line 40, in synthesize
    saver2.restore(sess, tf.train.latest_checkpoint(hp.logdir + "-2"))
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

How to solve this error please help me :(

**Comment by fathimad11** [comment]
Error is i did not run python train.py 2 ... after this i synthesize then  i got somewhat good result.
