### ISSUE TITLE
Error at train.py 1

### ISSUE THREAD

**Issue by b29b** [Kyubyong/dc_tts#76]
i tried this in colab with LJSpeech, tensorflow 1.x, python3. prepro.py ran without errors and got stuck at 

> python train.py 1

`Traceback (most recent call last):`
  `File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)`
  `File "/content/dc_tts/data_load.py", line 107, in _load_spectrograms
    mel = "mels/{}".format(fname.replace("wav", "npy"))`
`TypeError: a bytes-like object is required, not 'str'`

**Comment by b29b** [comment]
https://github.com/Kyubyong/dc_tts/pull/24/commits/a897f6ac51958744ff49aa5e28d4bf1265b71da4#
used the fix here, ram fills up before training finishes... 😔
