### ISSUE TITLE
Beginner problem

### ISSUE THREAD

**Issue by Crazyjoedevola** [Kyubyong/dc_tts#81]
Traceback (most recent call last):
  File "prepo.py", line 17, in <module>
    fpaths, _, _ = load_data() # list
  File "/content/dc_tts-master/data_load.py", line 65, in load_data
    fname, _, text, is_inside_quotes, duration = line.strip().split("|")
ValueError: not enough values to unpack (expected 5, got 3)

**Comment by Pritzier** [comment]
The data loader checks if the folder that contains the WAVS folder and transcript contain the word "LJ". If it contains "LJ" then only 3 values are expected, which is want you want I guess. You can of course change "LJ" to something else.

You are getting this ValueError, because your folder does not contain "LJ" and it, therefore, thinks you have formatted it differently.
